<?php

declare(strict_types=1);

namespace Subash\PhpPdf\Filter;

use Subash\PhpPdf\Exceptions\PdfParseException;

/**
 * Handles FlateDecode (zlib/DEFLATE) decompression used in compressed PDFs.
 */
class FlateDecode
{
    /**
     * Decompress a FlateDecode compressed stream.
     * Handles both full zlib format and raw DEFLATE.
     */
    public static function decompress(string $data): string
    {
        if (!extension_loaded('zlib')) {
            throw new PdfParseException('zlib extension is required for compressed PDF support');
        }

        // Try standard zlib
        $result = @gzuncompress($data);
        if ($result !== false) {
            return $result;
        }

        // Try raw DEFLATE (some PDFs skip the zlib header)
        $result = @gzinflate($data);
        if ($result !== false) {
            return $result;
        }

        // Try inflate_init(15) — handles zlib streams with sync flush (00 00 FF FF)
        // This covers PDFs generated by Adobe and other tools using Z_SYNC_FLUSH
        $ctx    = inflate_init(15);
        $result = @inflate_add($ctx, $data, ZLIB_SYNC_FLUSH);
        if ($result !== false && strlen($result) > 0) {
            return $result;
        }

        // Try raw deflate skipping 2-byte zlib header
        $ctx    = inflate_init(-15);
        $result = @inflate_add($ctx, substr($data, 2), ZLIB_SYNC_FLUSH);
        if ($result !== false && strlen($result) > 0) {
            return $result;
        }

        throw new PdfParseException('Failed to decompress FlateDecode stream');
    }

    /**
     * Apply inverse PNG predictor (Predictor >= 10) to decompressed stream data.
     * PDF xref streams and some content streams use PNG row predictors.
     *
     * @param string $data       Raw decompressed bytes (includes 1 filter byte per row)
     * @param array  $decodeParms Dictionary from /DecodeParms (keys without leading '/')
     */
    public static function applyPredictor(string $data, array $decodeParms): string
    {
        $predictor = (int) ($decodeParms['Predictor'] ?? 1);

        // Predictors < 10 are TIFF predictors or no-op — not used in PDF xref streams
        if ($predictor < 10) {
            return $data;
        }

        // PNG predictors (10–15): each row = 1 filter byte + $columns data bytes
        $columns = (int) ($decodeParms['Columns'] ?? 1);
        $rowSize = $columns + 1;
        $result  = '';
        $prior   = str_repeat("\x00", $columns);
        $len     = strlen($data);

        for ($i = 0; $i + $rowSize <= $len; $i += $rowSize) {
            $filterType = ord($data[$i]);
            $decoded    = '';

            for ($j = 0; $j < $columns; $j++) {
                $raw  = ord($data[$i + 1 + $j]);
                $up   = ord($prior[$j]);
                $left = $j > 0 ? ord($decoded[$j - 1]) : 0;

                switch ($filterType) {
                    case 0: // None
                        $decoded .= chr($raw);
                        break;
                    case 1: // Sub
                        $decoded .= chr(($raw + $left) & 0xFF);
                        break;
                    case 2: // Up
                        $decoded .= chr(($raw + $up) & 0xFF);
                        break;
                    case 3: // Average
                        $decoded .= chr(($raw + (int) (($left + $up) / 2)) & 0xFF);
                        break;
                    case 4: // Paeth
                        $priorLeft = $j > 0 ? ord($prior[$j - 1]) : 0;
                        $decoded   .= chr(($raw + self::paethPredictor($left, $up, $priorLeft)) & 0xFF);
                        break;
                    default:
                        $decoded .= chr($raw);
                }
            }

            $result .= $decoded;
            $prior   = $decoded;
        }

        return $result;
    }

    private static function paethPredictor(int $a, int $b, int $c): int
    {
        $p  = $a + $b - $c;
        $pa = abs($p - $a);
        $pb = abs($p - $b);
        $pc = abs($p - $c);
        if ($pa <= $pb && $pa <= $pc) return $a;
        if ($pb <= $pc) return $b;
        return $c;
    }

    /**
     * Compress data using FlateDecode (zlib).
     */
    public static function compress(string $data, int $level = 6): string
    {
        if (!extension_loaded('zlib')) {
            throw new PdfParseException('zlib extension is required for PDF compression');
        }

        $result = gzcompress($data, $level);

        if ($result === false) {
            throw new PdfParseException('Failed to compress data');
        }

        return $result;
    }
}
